name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "💥 Breaking changes"
    semver-increment: "major"
    when:
      labels: ["breaking"]
  - title: "🚀 Features"
    semver-increment: "minor"
    when:
      labels: ["enhancement"]
  - title: "🐛 Fixes"
    semver-increment: "patch"
    when:
      labels: ["bug"]
  - title: "🚜 Refactoring"
    semver-increment: "patch"
    when:
      labels: ["refactoring"]
  - title: "📝 Documentation"
    semver-increment: "patch"
    when:
      labels: ["documentation"]
  - title: "🏗️ Continuous integration"
    semver-increment: "patch"
    when:
      labels: ["ci"]
  - title: "📦 Dependencies"
    semver-increment: "patch"
    when:
      labels: ["dependencies"]
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
autolabeler:
  - label: "breaking"
    title: ["/!:/", "/^[a-z]+(\\(.+\\))?!:/i"]
  - label: "enhancement"
    title: ["/^feat/i"]
  - label: "bug"
    title: ["/^fix/i"]
  - label: "documentation"
    title: ["/^docs/i"]
  - label: "refactoring"
    title: ["/^refactor/i"]
  - label: "ci"
    title: ["/^ci/i", "/^chore/i", "/^build/i"]
  - label: "dependencies"
    title: ["/^deps/i", "/bump/i"]
template: |
  [![Downloads](https://img.shields.io/github/downloads/MrTomRocker/homeassistant-necromancer/v$RESOLVED_VERSION/total?color=success)](https://github.com/MrTomRocker/homeassistant-necromancer/releases/tag/v$RESOLVED_VERSION)

  ## Changes

  $CHANGES
