name: Feature request
description: Suggest an idea for Necromancer
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      description: What are you trying to achieve? What's frustrating with the current behaviour?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: A clear and concise description of what you'd like to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the request.
